In [ ]:
import pandas as pd

# Data frame for total wage records count by state alphabetically and year/quarter
count_total = wage_summary_Oracle_State.groupby(['QTR', 'YR', 'BLS_ID_COUNT', 'EIN_COUNT', 'TOTAL_WAGES', 'AVERAGE_WAGE', 'AVERAGE_WAGE_BLS'])\
    .agg({'TOTAL_RECORDS': 'sum'})\
    .pivot_table(index='STATE_CODE', columns=['QTR', 'YR'], values='TOTAL_RECORDS')\
    .reset_index()

count_total.columns = ['year_quarter'] + list(count_total.columns[1:])
count_total = count_total.sort_values(by=['year_quarter'], ascending=False)

# Data frame check for submitted wage records by state alphabetically and year/quarter
submission_check = count_total.copy()

# Replace any NaN values with 'X'
submission_check = submission_check.fillna('X')
submission_check = submission_check.sort_values(by=['year_quarter'], ascending=False)

# Data frame for percentage change by state alphabetically and year/quarter
percent_diff = wage_summary_Oracle_State.groupby('STATE_CODE').apply(
    lambda x: x.assign(percent_diff=((x['TOTAL_RECORDS'].diff() / x['TOTAL_RECORDS'].shift(1)) * 100))
).reset_index()

percent_diff['percent_diff'] = percent_diff['percent_diff'].round(2)

# Merge total wage records and percentage difference data frames
count_percent_diff = pd.merge(count_total, percent_diff, on='year_quarter', how='outer')

# Data frame for total wage records count and percentage change by state alphabetically and year/quarter
cpd = count_percent_diff.copy()
cpd = cpd.sort_values(by=['year_quarter'], ascending=False)

# Data frame for BLS ID count by state alphabetically and year/quarter
bls_id_count = wage_summary_Oracle_State.groupby(['QTR', 'YR', 'TOTAL_RECORDS', 'UI_COUNT', 'EIN_COUNT', 'TOTAL_WAGES', 'AVERAGE_WAGE_BLS'])\
    .agg({'BLS_ID_COUNT': 'sum'})\
    .pivot_table(index='STATE_CODE', columns=['QTR', 'YR'], values='BLS_ID_COUNT')\
    .reset_index()

bls_id_count.columns = ['year_quarter'] + list(bls_id_count.columns[1:])
bls_id_count = bls_id_count.sort_values(by=['year_quarter'], ascending=False)

# Data frame for UI count by state alphabetically and year/quarter
ui_count = wage_summary_Oracle_State.groupby(['QTR', 'YR', 'BLS_ID_COUNT', 'EIN_COUNT', 'TOTAL_WAGES', 'AVERAGE_WAGE_BLS'])\
    .agg({'UI_COUNT': 'sum'})\
    .pivot_table(index='STATE_CODE', columns=['QTR', 'YR'], values='UI_COUNT')\
    .reset_index()

ui_count.columns = ['year_quarter'] + list(ui_count.columns[1:])
ui_count = ui_count.sort_values(by=['year_quarter'], ascending=False)

In [ ]:
import pandas as pd

# Data frame for UI count by state alphabetically and year/quarter
ui_count = wage_summary_Oracle_State.groupby(['QTR', 'YR', 'TOTAL_RECORDS', 'BLS_ID_COUNT', 'EIN_COUNT', 'TOTAL_WAGES', 'AVERAGE_WAGE', 'AVERAGE_WAGE_BLS'])\
    .agg({'UI_COUNT': 'sum'})\
    .pivot_table(index='STATE_CODE', columns=['QTR', 'YR'], values='UI_COUNT')\
    .reset_index()

ui_count.columns = ['year_quarter'] + list(ui_count.columns[1:])
ui_count = ui_count.sort_values(by=['year_quarter'], ascending=False)

# Data frame for EIN count by state alphabetically and year/quarter
ein_count = wage_summary_Oracle_State.groupby(['QTR', 'YR', 'TOTAL_RECORDS', 'BLS_ID_COUNT', 'UI_COUNT', 'TOTAL_WAGES', 'AVERAGE_WAGE', 'AVERAGE_WAGE_BLS'])\
    .agg({'EIN_COUNT': 'sum'})\
    .pivot_table(index='STATE_CODE', columns=['QTR', 'YR'], values='EIN_COUNT')\
    .reset_index()

ein_count.columns = ['year_quarter'] + list(ein_count.columns[1:])
ein_count = ein_count.sort_values(by=['year_quarter'], ascending=False)

# Data frame for sum of total wages by state alphabetically and year/quarter
total_wages_sum = wage_summary_Oracle_State.groupby(['QTR', 'YR', 'TOTAL_RECORDS', 'BLS_ID_COUNT', 'EIN_COUNT', 'UI_COUNT', 'AVERAGE_WAGE', 'AVERAGE_WAGE_BLS'])\
    .agg({'TOTAL_WAGES': 'sum'})\
    .pivot_table(index='STATE_CODE', columns=['QTR', 'YR'], values='TOTAL_WAGES')\
    .reset_index()

total_wages_sum.columns = ['year_quarter'] + list(total_wages_sum.columns[1:])
total_wages_sum = total_wages_sum.sort_values(by=['year_quarter'], ascending=False)

# Data frame for average total wages by state alphabetically and year/quarter
average_wages = wage_summary_Oracle_State.groupby(['QTR', 'YR', 'TOTAL_RECORDS', 'BLS_ID_COUNT', 'EIN_COUNT', 'UI_COUNT', 'TOTAL_WAGES', 'AVERAGE_WAGE_BLS'])\
    .agg({'AVERAGE_WAGE': 'mean'})\
    .pivot_table(index='STATE_CODE', columns=['QTR', 'YR'], values='AVERAGE_WAGE')\
    .reset_index()

average_wages.columns = ['year_quarter'] + list(average_wages.columns[1:])
average_wages = average_wages.sort_values(by=['year_quarter'], ascending=False)

# Data frame for average total wages (BLS) by state alphabetically and year/quarter
average_wages_bls = wage_summary_Oracle_State.groupby(['QTR', 'YR', 'TOTAL_RECORDS', 'BLS_ID_COUNT', 'EIN_COUNT', 'UI_COUNT', 'TOTAL_WAGES', 'AVERAGE_WAGE'])\
    .agg({'AVERAGE_WAGE_BLS': 'mean'})\
    .pivot_table(index='STATE_CODE', columns=['QTR', 'YR'], values='AVERAGE_WAGE_BLS')\
    .reset_index()

average_wages_bls.columns = ['year_quarter'] + list(average_wages_bls.columns[1:])
average_wages_bls = average_wages_bls.sort_values(by=['year_quarter'], ascending=False)